## RAMADHANI FADHIL MOSHI

## Practical_6: Numpy

Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [140]:
import numpy as np

In [16]:
arry1 = np.arange(0, 10, 1)
arry1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [20]:
p = np.zeros((3,3))  
print(p)              
           

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [41]:
g = np.linspace(0, 5, 10)
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [5]:
A = np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [10]:
A = np.random.rand(4,4)
A

array([[0.03928443, 0.91279995, 0.31312712, 0.06371349],
       [0.44527603, 0.31589452, 0.02712727, 0.25211289],
       [0.13777378, 0.65606351, 0.51146626, 0.34253516],
       [0.35835552, 0.6679604 , 0.02335373, 0.88408903]])

In [13]:
np.random.seed(10)
A = np.random.rand(4,4)
A

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [3]:
np.random.seed(0)
A = np.random.rand(4,4)
A

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

Exercise 6:
Find the shape of a NumPy array.

In [5]:
A.shape

(4, 4)

Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [397]:
new_array = A.reshape(3,3)
new_array

array([[2, 3, 4],
       [1, 2, 5],
       [1, 0, 1]])

Exercise 8:
Find the data type of the elements in a NumPy array.

In [11]:
A.dtype

dtype('float64')

Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [21]:
A = np.arange(2, 101, 2)
A

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [14]:
A = np.random.randint(10, 50, (6,6))
A

array([[26, 15, 25, 10, 28, 45],
       [34, 39, 29, 29, 24, 49],
       [42, 11, 19, 42, 41, 20],
       [33, 45, 21, 38, 44, 10],
       [10, 46, 15, 48, 27, 25],
       [14, 41, 11, 11, 49, 45]])

Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [38]:
a = np.array([[10,4,5], [5,6,2],[1,2,3]])
b = a[:2, 0:2]
print(b)

[[10  4]
 [ 5  6]]


Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [40]:
C = np.arange(0, 10, 1)
sum = 0
for i in C:
    sum+=i
print(sum)


45


Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [50]:
B = np.array([2, 4, 5, 3, 9,6,5,12,8,10])
np.mean(B)


3.0724582991474434

In [52]:
np.median(B)


5.5

In [56]:
np.std(B, ddof = True)

3.2386554137309647

Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [61]:
B = np.array([2, 4, 5, 3, 9,6,5,12,8,10])
np.max(B)

12

In [63]:
np.min(B)

2

Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [76]:
A = np.random.randint(1,50, size=20)
maxvalue = np.argmax(A)
print(A)
print(maxvalue)

[31 25  3  4 31 35 44 14 49 41  9 20 32  9 27  3  4 45 15 33]
8


Exercise 16:
Create a NumPy array and reverse its elements.

In [79]:
B = np.array([2, 4, 5, 3, 9,6,5,12,8,10])
B2 = B[::-1]
B2

array([10,  8, 12,  5,  6,  9,  3,  5,  4,  2])

Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [103]:
A = np.array([[1,2,3],[3,2,4],[1,5,3]])
B = np.array([[2,2,2],[3,1,4],[1,4,3]])
print(A)
print(B)

[[1 2 3]
 [3 2 4]
 [1 5 3]]
[[2 2 2]
 [3 1 4]
 [1 4 3]]


In [109]:
print(A*B)

[[ 2  4  6]
 [ 9  2 16]
 [ 1 20  9]]


Exercise 18:
Create a diagonal matrix from a given 1D array.

In [111]:
C = np.diag([7,7,7])
C

array([[7, 0, 0],
       [0, 7, 0],
       [0, 0, 7]])

Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [116]:
x = np.array([[2,2],[2,4]])
y = np.array([[5,1],[7,2]])
print(np.dot(x, y))


[[24  6]
 [38 10]]


Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [125]:
x = np.array([[2,2],[2,4]])
x.flatten()

array([2, 2, 2, 4])

Exercise 21:
Stack two NumPy arrays vertically.

In [135]:
a= np.array([[2,2],[2,4]])
b = np.array([[5,1],[7,2]])
np.vstack((a, b))

array([[2, 2],
       [2, 4],
       [5, 1],
       [7, 2]])

Exercise 22:
 Stack two NumPy arrays horizontally.

In [160]:
a= np.array([[2,2],[2,4]])
b = np.array([[5,1],[7,2]])
np.hstack((a, b))

array([[2, 2, 5, 1],
       [2, 4, 7, 2]])

Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [174]:
arr = np.array([2, 2, 5, 1,2, 4, 7, 2])
arr1 = arr[:4]
arr2 = arr[4:]
print(arr1)
print(arr2)

[2 2 5 1]
[2 4 7 2]


Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [187]:
Z = np.random.random(10)
R= np.round(Z, 2)
R

array([0.37, 0.44, 0.89, 0.81, 0.7 , 0.1 , 0.92, 0.71, 1.  , 0.15])

Exercise 25:
Find the unique elements of a NumPy array.

In [194]:
array1 = np.array([2,3,4,2,5,6,3,5,7])
x = np.unique(array1)
print(x)

[2 3 4 5 6 7]


Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [213]:
array1 = np.array([2,3,4,2,5,6,3,5,7])
q=3
array1[array1 < q]=q
print(array1)


[3 3 4 3 5 6 3 5 7]


Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [220]:
array1 = np.array([2,3,4,2,5,6,3,5,7])
print(np.cumsum(array1))

[ 2  5  9 11 16 22 25 30 37]


Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [235]:
array1 = np.array([3,3,0,2,5,0,3,5,7])
print(np.count_nonzero(array1))

7


Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [242]:
array2 = np.random.randint(1, 50, size=20)
np.sort(array2)

array([ 2,  4,  6,  9, 12, 17, 18, 26, 28, 30, 31, 34, 35, 36, 36, 37, 40,
       41, 49, 49])

Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [254]:
array2 = np.random.randint(1, 50, size=(3,3))
print(array2)
print("row sum", np.sum(array2, axis=1))
print("column sum", np.sum(array2, axis=0))

[[18 42  1]
 [23 17 43]
 [37 31 25]]
row sum [61 83 93]
column sum [78 90 69]


Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [287]:
array3 = np.random.rand(3,3)
print(array3)
normalized_array3 = (array3 - np.min(array3)) / (np.max(array3) - np.min(array3))
print("=====================")
print("normalized_array3")

print(normalized_array3)

[[0.47837031 0.49739137 0.63947252]
 [0.36858461 0.13690027 0.82211773]
 [0.18984791 0.51131898 0.22431703]]
normalized_array3
[[0.4983382  0.52609735 0.73344927]
 [0.33811797 0.         1.        ]
 [0.07727129 0.54642319 0.1275752 ]]


Exercise 32:
Create two NumPy arrays and find the dot product.

In [275]:
A = np.array([[2,3,4],[1,2,5],[1,0,1]])
B = np.array([[2,3,4],[1,2,5],[1,1,1]])
print(np.dot(A,B))


[[11 16 27]
 [ 9 12 19]
 [ 3  4  5]]


Exercise 33:
Find the trace of a square NumPy matrix.

In [290]:
A = np.array([[2,3,4],[1,2,5],[1,0,1]])
np.trace(A)

5

Exercise 34:
Create a 2D array and swap two rows.

In [299]:
A = np.array([[2,3,4],[1,2,5],[1,0,1]])
print(A)
row1=1
row1=2
A[[1, 2]] = A[[2, 1]]
print("=====================")
print("after swaping row1 and row2")

A


[[2 3 4]
 [1 2 5]
 [1 0 1]]
after swaping row1 and row2


array([[2, 3, 4],
       [1, 0, 1],
       [1, 2, 5]])

Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [308]:
array4 = np.array([2,3,4,5])
array5 = array4.reshape(4,1)
print(array5)

[[2]
 [3]
 [4]
 [5]]


Exercise 36:
Find the determinant of a 3x3 matrix.

In [321]:
A = np.array([[2,3,4],[1,2,5],[1,0,1]])
D = np.linalg.det(A)
print("the determinant of matrix A is ", D)

the determinant of matrix A is  7.999999999999998


Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [326]:
A = np.array([[3,4],[2,5]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("===============================================")
print("eigenvalues is ", eigenvalues)

print("===============================================")
print("eigenvectors is ", eigenvectors)


eigenvalues is  [1. 7.]
eigenvectors is  [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Exercise 38:
Solve a system of linear equations using NumPy.

In [335]:
# 1x+3y=5
# 3x+4y=7

A = np.array([[1,3],[3,4]])
B = np.array([5,7])

answer = np.linalg.solve(A, B)
print("(x,y) is ", answer)

(x,y) is  [0.2 1.6]


Exercise 39:
Add Gaussian noise to a NumPy array.

In [342]:
y = np.random.normal(size = (2, 3))
y

array([[-0.54286148,  0.41605005, -1.15618243],
       [ 0.7811981 ,  1.49448454, -2.06998503]])

Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [345]:
A = np.array([[2,3,4],[1,2,5],[1,0,1]])
np.diag(A)

array([2, 2, 1])

Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

In [360]:
array7 = np.random.rand(100) * 100
np.clip(array7, 10, 50)

array([34.9440292 , 50.        , 50.        , 50.        , 10.        ,
       50.        , 39.25687885, 50.        , 50.        , 50.        ,
       50.        , 36.4544626 , 50.        , 37.63891552, 36.4911836 ,
       26.09044994, 49.59702954, 50.        , 27.73402713, 50.        ,
       11.73802942, 15.98452869, 10.        , 50.        , 10.        ,
       17.85799681, 50.        , 10.        , 50.        , 50.        ,
       50.        , 50.        , 30.04036832, 50.        , 50.        ,
       50.        , 26.72070319, 50.        , 37.19187485, 10.        ,
       24.76850225, 31.82335092, 50.        , 45.85031671, 44.45872878,
       33.61022664, 50.        , 50.        , 50.        , 37.6741267 ,
       50.        , 50.        , 50.        , 24.48894794, 21.64572609,
       16.60478245, 50.        , 29.40766624, 45.30942454, 49.3957834 ,
       50.        , 50.        , 13.90727011, 42.69043602, 50.        ,
       50.        , 10.24137585, 15.63833489, 30.41986916, 10.  

Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

In [379]:
A = np.array([[2,-3,4],[1,2,-5],[1,8,1]])
x = 0
A[A < x] = x
A

array([[2, 0, 4],
       [1, 2, 0],
       [1, 8, 1]])

Exercise 43:
Find the inner and outer products of two NumPy arrays.

In [388]:
A = np.array([[2,3,4],[1,2,5],[1,0,1]])
B = np.array([[2,3,4],[1,2,5],[1,1,1]])

print("inner product")

print(np.inner(A,B))
print("=============================================")

print("outer product")
print(np.outer(A, B))

inner product
[[29 28  9]
 [28 30  8]
 [ 6  6  2]]
outer product
[[ 4  6  8  2  4 10  2  2  2]
 [ 6  9 12  3  6 15  3  3  3]
 [ 8 12 16  4  8 20  4  4  4]
 [ 2  3  4  1  2  5  1  1  1]
 [ 4  6  8  2  4 10  2  2  2]
 [10 15 20  5 10 25  5  5  5]
 [ 2  3  4  1  2  5  1  1  1]
 [ 0  0  0  0  0  0  0  0  0]
 [ 2  3  4  1  2  5  1  1  1]]
